FROM python:3.12-alpine


WORKDIR /app

COPY app-v1/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app-v1/ . 

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]