name: FastAPI Microservices CI/CD Pipeline

on:
  workflow_dispatch:

  
jobs:
  build:
    runs-on: self-hosted


    steps:
    - name: Check out code
      uses: actions/checkout@v6
      with:
        ref: feat/1

    - name: Stop and remove existing containers
      run: |
        docker stop fastapi-app-v1-container fastapi-app-v2-container || true
        docker rm fastapi-app-v1-container fastapi-app-v2-container || true

    - name: Remove existing images
      run: |
        docker rmi fastapi-app-v1 fastapi-app-v2 || true
    
    - name: docker build for v1
      run: |
        docker build -t fastapi-app-v1 -f app-v1/Dockerfile .
    
    - name: docker build for v2
      run: |
        docker build -t fastapi-app-v2 -f app-v2/Dockerfile .

    - name: Run the docker image for v1
      run: |
        docker run -d -p 8000:8000 --name fastapi-app-v1-container fastapi-app-v1

    - name: Run the docker image for v2
      run: |
        docker run -d -p 8001:8001 --name fastapi-app-v2-container fastapi-app-v2

